### ISSUE TITLE
TSLint/ESlint JUnit format

### ISSUE THREAD

**Issue by joscha** [bugcrowd/test-summary-buildkite-plugin#19]
The [Junit format that tslint spits out](https://palantir.github.io/tslint/formatters/junit/) via `tslint --format junit --out junit.xml` looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites package="tslint">
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/editing/charts/stories/shapes.stories.tsx">
        <testcase name="Line 1, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/main.tsx">
        <testcase name="Line 75, Column 13: quotemark">
            <failure type="error">&quot; should be &#39;</failure>
        </testcase>
        <testcase name="Line 75, Column 9: no-unused-variable">
            <failure type="error">&#39;x&#39; is declared but its value is never read.</failure>
        </testcase>
        <testcase name="Line 75, Column 18: semicolon">
            <failure type="error">Missing semicolon</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/publish/design_spec_menus/create/stories/create_design_menu.stories.tsx">
        <testcase name="Line 4, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/search/object_panel/object_panel_configuration.ts">
        <testcase name="Line 3, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/tailoring/assistant/panel/panel.tsx">
        <testcase name="Line 3, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/pages/editor/tailoring/assistant/static_cards/welcome_card/welcome_card_messages.ts">
        <testcase name="Line 1, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/ui/publish/menu/print/address_autocomplete_input/stories/address_autocomplete_input.stories.tsx">
        <testcase name="Line 4, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/ui/publish/menu/print/order_details/page_select/tests/page_select.tests.tsx">
        <testcase name="Line 3, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
    <testsuite name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/src/ui/publish/menu/print/proofing_flow/proofing_flow/proofing_flow_presenter.ts">
        <testcase name="Line 3, Column 1: no-unused-variable">
            <failure type="error">All imports on this line are unused.</failure>
        </testcase>
    </testsuite>
</testsuites>
```

which unfortunately results in something unreadable like this:

![tslint](https://user-images.githubusercontent.com/188038/42013157-44d6cc1a-7adf-11e8-897d-8c45b94e93c8.png)

any chance we could resolve a `name` attribute of a testsuite to a file path and use that as the information in the generated annotation if it starts with `${BUILDKITE_BUILD_PATH}`?

Happy to open a pull request!

**Comment by joscha** [comment]
Actually it seems as if `eslint` has a similar issue:

![web__test_base__23312](https://user-images.githubusercontent.com/188038/42015474-dbc01946-7aea-11e8-92e9-5bdb9fb385d0.png)

via:
```xml
<testsuites>
<testsuite package="org.eslint" time="0" tests="2" errors="2" name="/var/lib/buildkite-agent/builds/my-org/my-pipeline/web/bin/install_selenium.js">
<testcase time="0" name="org.eslint.no-unused-vars">
<failure message="'x' is assigned a value but never used.">
<![CDATA[
line 16, col 9, Error - &apos;x&apos; is assigned a value but never used. (no-unused-vars)
]]>
</failure>
</testcase>
<testcase time="0" name="org.eslint.semi">
<failure message="Missing semicolon.">
<![CDATA[ line 16, col 14, Error - Missing semicolon. (semi) ]]>
</failure>
</testcase>
</testsuite>
</testsuites>
```

**Comment by joscha** [comment]
Additionally, we need to decode the html entities inside the CDATA field.

**Comment by tessereth** [comment]
Thanks for this! More examples are always appreciated. Each time someone comes up with another example I'm both happy that this thing gets a bit better and sad about how inconsistent junit really is...

I'll have a more detailed look in a bit but a couple things that come to mind on a first pass.

1. Each junit formatter seems to put different information in different places. I need to have a think about how to turn that into a useful oneliner for the summary in the general case. (We're using rspec which puts the line number in the body of the testcase which is particularly useless.) But we could definitely include more stuff in the details. 
2. The contents of CDATA is not supposed to be html escaped. If eslint is doing that, they probably shouldn't.
3. Linters often produce fairly sane "single line per error" output because they don't have that much detail beyond a file, line and brief message. We use the `emacs` formatter for eslint and it looks like tslint has something similar (prose/verbose formatters). Have you given those a go with the `oneline` input type?
4. I should really fix that bug when you have an empty message...

**Comment by joscha** [comment]
It seems eslint introduced this escaping due tho control characters: https://github.com/eslint/eslint/pull/6672 - so I doubt I can make them remove it easily - technically I guess we should be able to remove the CDATA section and it would still be valid XML (because every character in there is escaped), but I think that would be a breaking change to their format.

**Comment by joscha** [comment]
opened https://github.com/eslint/eslint/issues/10537

**Comment by joscha** [comment]
@tessereth would you accept a PR to support checkstyle? For linters that seems to be the best format, see https://palantir.github.io/tslint/formatters/checkstyle/ and https://eslint.org/docs/user-guide/formatters/#checkstyle

**Comment by tessereth** [comment]
If you really want to implement checkstyle, go for it. I'll accept the PR (assuming it has tests etc). But I'm not sure you really need it. As far as I can tell, the eslint unix and tslint verbose formatters have all the relevant information. And all a checkstyle input type here would do is convert the structured information into a summary that looks much the same. But hey, if you want to go for it, go for it.

**Comment by tessereth** [comment]
Just realized I said we use the `emacs` formatter for eslint. That's wrong, we use `unix` for eslint. We use `emacs` for rubocop. They look basically the same, that's why I get them muddled up. Sorry for any confusion.

**Comment by joscha** [comment]
agreed, making good progress with the oneline format, stripping off the repository root makes it really readable:

```bash
REPO_DIR=$(git rev-parse --show-toplevel)

output_file="target/tslint-${BUILDKITE_JOB_ID:-0}.txt"
tslint --format msbuild \
       --out "${output_file}"
sed -i.bak "s#${REPO_DIR}/##g" "${output_file}"
```

so I think I will be fine with that for now. The reason I was thinking checkstyle was, because then you could actually link back to the file, using the file, line and  column from within the summary, which would be quite nice.

> Just realized I said we use the emacs formatter for eslint. That's wrong, we use unix for eslint. We use emacs for rubocop. They look basically the same, that's why I get them muddled up. Sorry for any confusion.

I chose `compact`, as that one starts with the file name, which makes it easier to read.

**Comment by joscha** [comment]
was able to make it all work with the `oneline` type.
