### ISSUE TITLE
Annotation fails with large number of test failures

### ISSUE THREAD

**Issue by paulfri** [bugcrowd/test-summary-buildkite-plugin#8]
```
Failed to annotate build: POST https://agent.buildkite.com/v3/jobs/0fd9db38-9c2b-4360-970a-cde6b566d44b/annotations: 400 The annotation body must be less than 50 kilobytes
```

Ideally this would truncate after a certain number of failures, but instead it fails entirely.

**Comment by tessereth** [comment]
You just need to write better code :trollface: 

I was wondering what that limit was going to be. Thanks for reporting it. I'll figure something out.
